### ISSUE TITLE
Runs and fails on master branches of forks

### ISSUE THREAD

**Issue by ozscheyge** [ePages-de/tech-writer-notify#2]
When developers update the `master` branch of their forks, the action will run there and fail.

## Expected

* tech-writer-notify is run only for upstream `ePages-de` repositories

## Hints

https://github.community/t/stop-github-actions-running-on-a-fork/17965

**Comment by ozscheyge** [comment]
See fixes:

https://github.com/ePages-de/ng-add-on/pull/219
https://github.com/ePages-de/ng-auth/pull/708
https://github.com/ePages-de/ng-customer/pull/190
https://github.com/ePages-de/ng-order/pull/1079
https://github.com/ePages-de/ng-payment-gateway/pull/274
https://github.com/ePages-de/ng-product-management/pull/1054
https://github.com/ePages-de/ng-product-view/pull/632
https://github.com/ePages-de/ng-shop/pull/797
https://github.com/ePages-de/ng-storefront-app-data/pull/63
https://github.com/ePages-de/ng-webhook/pull/137

**Comment by jmewes** [comment]
The solution is to specify the repo in which the action is supposed to run, as shown in the README:

https://github.com/ePages-de/tech-writer-notify/blame/9b868bc/README.md#L23
